apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment-frontend
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: {{ .Values.targetCPUUtilizationPercentage}}