apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-volume
    labels:
        type: local
spec:
    storageClassName: hostpath
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
